all: 
	$(error Obj files were edited with a hex editor to generate the ld_abs operations)

# ld_abs_b:
# 	clang -O2 -emit-llvm -c ld_abs_b.c -o - | /usr/local/opt/llvm/bin/llc -march=bpf -filetype=obj -o ld_abs_b.o 

# ld_abs_h:
# 	clang -O2 -emit-llvm -c ld_abs_h.c -o - | /usr/local/opt/llvm/bin/llc -march=bpf -filetype=obj -o ld_abs_h.o 

# ld_abs_w:
# 	clang -O2 -emit-llvm -c ld_abs_w.c -o - | /usr/local/opt/llvm/bin/llc -march=bpf -filetype=obj -o ld_abs_w.o 

# ld_abs_dw:
# 	clang -O2 -emit-llvm -c ld_abs_dw.c -o - | /usr/local/opt/llvm/bin/llc -march=bpf -filetype=obj -o ld_abs_dw.o 

# clean:
# 	rm -rf *.o